Some small changes to aid mingw compilers. (#35)
* Add include stdio.h for sprintf_s and _snprintf.

error: ‘sprintf_s’ was not declared in this scope
error: ‘_snprintf’ was not declared in this scope

* Add include stdlib.h for atoi.

* Add include shlwapi.h for DLLVERSIONINFO.

* Remove class name from method declaration.

* Avoid reserved keyword xor or default.

* Switch comments in deadKeyMap for +U00A8 and +U00B4.

* Move #endif to the matching if block.

* Avoid warning "extra tokens at end of #endif directive".

* Cast void pointer to do arithmetic.

error: invalid operands of types ‘rdr::U8*’ {aka ‘unsigned char*’} and ‘const void*’ to binary ‘operator-’