Update Windows with regular Visual Studio project files -to-> Windows with regular Visual Studio project files (with MFC components to avoid errors about missing afxres.h) + VS Build Tools 2019 same error + Errors MSB8036 -Download and install-> Windows SDK Version 8.1 + for fatal error C1083 -Install-> "MSVC v140 - VS 2015 C++ Build Tools (v14.00)" = No Errors 	modified:   cmake/readme.txt